"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# .env 로드
load_dotenv(os.path.join(BASE_DIR, ".env"))
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "default-secret-key-if-not-set")

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# DEBUG가 False일 때, Django 애플리케이션이 응답할 수 있는 호스트를 정의. 개발 환경에서는 'localhost'와 '127.0.0.1'을 포함.
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'apps.main',
    'apps.chatbot',
    'apps.accounts',
    'apps.admin_ui',
    'apps.rag',
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware', # 디버그 툴바
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = [
    "127.0.0.1", # 디버그 툴바는 INTERNAL_IPS에 지정된 주소에서 표시
    # "192.168.1.100", # 만약 다른 기기에서 접근할 경우 해당 IP도 추가
]

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: True, # 모든 요청에 툴바 표시 (임시)
    "INTERCEPT_REDIRECTS": True,
    "ENABLE_STACKTRACES": True,
    "RESULTS_CACHE_SIZE": 100,
    "SHOW_PRIVATE_PROFILERS": True,
    "ROOT_TAG_ATTRS": 'class="dbt"',
    "AJAX_REQUESTS": True,
}

ROOT_URLCONF = 'config.urls'

# 🔹 전역 base.html 및 각 앱 템플릿 모두 인식 가능하도록
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 전역 base.html
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "ko-kr"

# TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Seoul"

USE_I18N = True

# USE_TZ = True
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# 🔹 정적 파일 설정: 전역 static/ + 각 앱 static 포함 가능
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # main.js가 프로젝트 루트의 static 폴더에 있다면 이 경로가 있어야 합니다.
    # 다른 앱의 static 폴더가 있다면 추가
]

# collectstatic 명령어가 정적 파일을 모을 최종 경로 (DEBUG=False일 때 Nginx/Apache 등 웹 서버가 서빙)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # 최종 모아질 디렉토리

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.CustomUser' # '앱이름.모델이름' 형식


# 세션 관련 설정
# 브라우저가 닫힐 때 세션 쿠키가 만료되도록 설정
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

"""
# 로그인 로거
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': { # Django 자체 로그 (HTTP 요청 등)
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.accounts': { # <--- 이 부분이 중요합니다. apps/accounts/views.py의 로거
            'handlers': ['console'],
            'level': 'DEBUG', # 반드시 DEBUG 또는 INFO로 설정해야 합니다.
            'propagate': False,
        },
        # 다른 앱의 로거가 있다면 여기에 추가
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING', # 기본 루트 로거 레벨
    },
}
"""
